feat: Add Show Index
halverneus/static-file-server pull request #80
Opened 2022-08-05 06:44 UTC by yankay

To fix the https://github.com/halverneus/static-file-server/issues/74, the solution is aim to add a Show Index args, so that the user can use 
```
SHOW_INDEX=true
SHOW_LISTING=false
```
to serve the static file more security

2022-08-05 06:44 UTC, yankay commented
HI @halverneus , would you please to review it

2022-08-05 16:21 UTC, halverneus requested changes
I like what you have done, but I think we can slightly improve upon the implementation. With the code in this PR, this works (assuming each path has an `index.html`):

`http://somewhere.com/`

but this doesn't:

`http://somewhere.com/nested/`

As a suggestion, instead of modifying `IgnoreIndex()`, perhaps add the following:

```go
// PreventListings returns a function that prevents listing of directories but
// still allows index.html to be served.
func PreventListings(serve http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if strings.HasSuffix(r.URL.Path, "/") {
			// If the directory does not contain an index.html file, then
			// return 'NOT FOUND' to prevent listing of the directory.
			stat, err := os.Stat(path.Join(r.URL.Path, "index.html"))
			if err != nil || !stat.Mode().IsRegular() {
				http.NotFound(w, r)
				return
			}
		}
		serve(w, r)
	}
}
```

With that, the handler logic might look something like:

```go
// Determine whether index files should hidden.
if !config.Get.ShowListing {
    if config.Get.AllowIndex {
        handler = handle.PreventListings(handler)
    } else {
        handler = handle.IgnoreIndex(handler)
    }
}
```

Where, to preserve previous behavior:

```bash
# Automatically serve the index file for a given directory (default). If set to
# 'false', URLs ending with a '/' will return 'NOT FOUND' unless ALLOW_INDEX is
# set to true, in which case directory listings are suppressed but index.html
# files are served, if present.
SHOW_LISTING=true

# Allow index file to be served even if SHOW_LISTING is set to false. This
# variable is only evaluated when SHOW_LISTING is false.
ALLOW_INDEX=false
```

Does that seem reasonable?

2022-08-08 03:37 UTC, yankay commented
HI @halverneus , I have change the codes with 'allow-index', would you please review it ?

2022-08-08 19:10 UTC, halverneus requested changes
Just two small changes: Removal of unused code and addition of a single unit test case.

Otherwise, looks great! Once those to changes are done, I'll merge it right away. Thank you very much for this contribution!

2022-08-08 19:10 UTC, halverneus commented on handle/handle_test.go
> +		{"Good subdir file", tmpSubFileName, ok, tmpSubFile},
For 100% coverage, can you add:

1. In the variables at the top of `handle_test.go`, right after the assignment of `tmpSubDeepBadName` variables for `tmpNoIndexDir` and `tmpNoIndexName`:

```go
var (
	baseDir             = "tmp/"
	...
	tmpSubDeepBadName   = "sub/deep/bad.txt"
	tmpNoIndexDir       = "noindex/"                     <--
	tmpNoIndexName      = "noindex/noindex.txt"          <--
```

Then add `tmpNoIndexName` to files (can re-use another file's contents, as shown):

```go
files = map[string]string{
    baseDir + tmpIndexName:        tmpIndex,
    ...
    baseDir + tmpSubDeepFileName:  tmpSubDeepFile,
    baseDir + tmpNoIndexName:      tmpSubDeepFile,       <--
}
```

Which then makes it possible to test the case where there is a directory without an `index.html` file:

```go
{"Good subdir file", tmpSubFileName, ok, tmpSubFile},
{"Dir without index", tmpNoIndexDir, missing, notFound},  <--
```

2022-08-11 15:50 UTC, merged

2022-08-13 03:42 UTC, yankay commented
Thanks @halverneus